language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecov coverage pandas pytest pytz

script:
  - coverage run setup.py test

after_success:
  - codecov
