language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - NUMPY=1.14.0
  - NUMPY=1.13.0
  - NUMPY=1.12.0
  - NUMPY=1.11.0
  - NUMPY=1.10.0

install:
  - pip install -q numpy==$NUMPY
  - pip install pandas pytest pytz

script:
  - python -m pytest
